CREATE TABLE `need` (
  `need_id` varchar(128) NOT NULL COMMENT '需求号',
  `need_type` varchar(64) NOT NULL COMMENT '类型:勤工俭学(workStudy)、公益活动(publicBenefit)、特色课程(course)',
  `time` varchar(128) NOT NULL COMMENT '时间（xx月xx日，字符串）',
  `title` varchar(128) NOT NULL COMMENT '需求标题',
  `description` varchar(1024) NOT NULL COMMENT '需求描述',
  `address_name` varchar(1024) NOT NULL COMMENT '地点名（API获取) ',
  `longitude` BIGINT(6) NOT NULL COMMENT '经度',
  `latitude` BIGINT(6) NOT NULL COMMENT '纬度',
  `address_description` varchar(1024) NOT NULL COMMENT '地点描述',
  `reward` varchar(128) NOT NULL COMMENT '报酬',
  `number_of_sign_up` BIGINT(6) NOT NULL COMMENT '可报名人数',
  `publish_time` BIGINT(6) NOT NULL COMMENT '发布时间（时间戳）',
  `publisher_name` varchar(64) NOT NULL COMMENT '发布者名字（如：食堂，学校，xx社团）',
  `publisher_id` varchar(128) NOT NULL COMMENT '发布人（类型为userID，因为需要根据权限进行判断）',
  `reviewer_id` varchar(128) NOT NULL COMMENT '审核人（类型为adminID，因为需要权限固定，由后端填写）',
  `state` varchar(64) NOT NULL COMMENT '状态：报名（signUp)(默认)、终止(stop)、待审核（wait)(之后的需求，现在用不上）',
  `signed_up` BIGINT(6) NOT NULL COMMENT '已报名人数，便于报名逻辑处理',
  PRIMARY KEY (`need_id`),
  KEY `FK_Need_Publisher` (`publisher_id`),
  CONSTRAINT `FK_Need_Publisher` FOREIGN KEY (`publisher_id`) REFERENCES `user` (`user_id`),
  KEY `FK_Need_Reviewer` (`reviewer_id`),
  CONSTRAINT `FK_Need_Reviewer` FOREIGN KEY (`reviewer_id`) REFERENCES `admin` (`admin_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '需求';
